### ISSUE TITLE
Cosas del chat

### ISSUE THREAD

**Issue by victoriagnatiuk** [IW-G2/GoTour#55]
Arreglar  la foto del avatar. Ahora las imagenes funcionan distinto.
Añadir la barra de busqueda.
Hacer que cuando se añade un mensaje se autoscrolle para abajo.
No permitir enviar mensajes vacios.

**Comment by jesuss07** [comment]
el subscribe hay que hacerle, lo suyo seria hacer una funcion que suscribiera al usuario a todos sus topics según iniciara sesion

**Comment by jesuss07** [comment]
> cuando hacemos el topic, guardarlo en tour en la bd, y el topic en lugar de ser el id sea una cadena rara para que solo los pertenecientes al tour puedan acceder

Osease, al crear un tour concreto se crea el topic, que se guardará como atributo de dicho tour

**Comment by victoriagnatiuk** [comment]
Añadir el botón al chat
